# Generated by Django 5.2.6 on 2025-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
